### ISSUE TITLE
highlighting breaks in other modes

### ISSUE THREAD

**Issue by busterbenson** [gf3/haml.mode#1]
I'm not sure how this could be happening, but ever since installing this HAML mode, my syntax highlighting in other modes (like erb) often gets out of sync.  I have to copy and paste the full file for it to fix itself.  I uninstalled HAML mode and the problem went away.  Is this a known problem or does anyone know of a fix for it?

**Comment by gf3** [comment]
Very strange, I'll have to look into it! Thanks.

**Comment by hilukasz** [comment]
this works almost out of the box for jade too. still leaves some things to be desired, but better solution than none!
